version: '3.4'

services:
  db:
    env_file: ".env"
    ports:
      - 5432:5432
    image: postgres
    #network_mode: "host"
    restart: always
    shm_size: 128mb

  backend:
    restart: always
    env_file: ".env"
    image: mgamersapi
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    depends_on:
      - db

  frontend:
    image: mgamerswebapp
    env_file: ".env"
    build: 
      context: ./frontend/mgamerswebapp
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
