version: '3.4'

services:
  db:
    env_file: ".env"
    ports:
      - 5432:5432
    image: postgres
    #network_mode: "host"
    restart: always
    shm_size: 128mb

  backend:
    restart: always
    env_file: ".env"
    image: mgamersapi
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  frontend:
    image: mgamerswebapp
    env_file: ".env"
    build: 
      context: ./frontend/mgamerswebapp
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_DOMAIN=http://localhost:8080
    restart: always
    ports:
      - 3000:3000

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/conf/Caddyfile.yml:/etc/caddy/Caddyfile.yml
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
